### ISSUE TITLE
Won't compile 

### ISSUE THREAD

**Issue by Gamedev1909** [pcsx3/pcsx3#1]
Build started
git clone -q --branch=master https://github.com/Gamedev1909/pcsx3.git C:\projects\pcsx3
git checkout -qf d65733193e18b5670769d2578777d18fe58a5d28
msbuild "C:\projects\pcsx3\pcsx3.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 12.0.40629.0
[Microsoft .NET Framework, version 4.0.30319.36366]
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\projects\pcsx3\pcsx3\pcsx3.vcxproj]
Command exited with code 1

**Comment by georgemoralis** [comment]
it looks to me that you are trying to compile with an earlier vstudio (probably 2013 ?) . Anyway still there isn't much to look here so i don't think it's important for now

**Comment by Gamedev1909** [comment]
nope tried 2015 update 3 and then 2017 rc both failed

**Comment by hlide** [comment]
Please refrain yourself to post that kind of issue at this stage.
